### ISSUE TITLE
Errore nell'esecuzione del TASK openldap:ldap_entry di playbook.yml

### ISSUE THREAD

**Issue by UniBean** [ConsortiumGARR/IdP3-vagrant#1]
Buongiorno,
dopo aver seguito tutti i passaggi della guida ed essere arrivato all'esecuzione del comando "ansible-playbook playbook.yml -i hosts", lo stesso termina con errore durante l'esecuzione del TASK "openldap: ldap_entry".

Ho provato anche a rilanciare il tutto con l'opzione "--limit @/root/IdP3-ansible/playbook.retry" ma senza ottenere nessun beneficio.

Potreste aiutarmi?
Grazie in anticipo
Francesco

Di seguito incollo estratto del log (ottenuto con l'opzione -vvv)

TASK [openldap : ldap_entry] ********************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: ('expected a string in the list', ['organizationalUnit', 'top'])
failed: [localhost] (item={u'ou': u'People', u'name': u'people'}) => {"changed": false, "details": "('expected a string in the list', ['organizationalUnit', 'top'])", "item": {"name": "people", "ou": "People"}, "msg": "Entry action failed."}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: ('expected a string in the list', ['organizationalUnit', 'top'])
failed: [localhost] (item={u'ou': u'Groups', u'name': u'groups'}) => {"changed": false, "details": "('expected a string in the list', ['organizationalUnit', 'top'])", "item": {"name": "groups", "ou": "Groups"}, "msg": "Entry action failed."}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: ('expected a string in the list', ['organizationalUnit', 'top'])
failed: [localhost] (item={u'ou': u'System', u'name': u'system'}) => {"changed": false, "details": "('expected a string in the list', ['organizationalUnit', 'top'])", "item": {"name": "system", "ou": "System"}, "msg": "Entry action failed."}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: ('expected a string in the list', ['organizationalUnit', 'top'])
failed: [localhost] (item={u'ou': u'Policies', u'name': u'policies'}) => {"changed": false, "details": "('expected a string in the list', ['organizationalUnit', 'top'])", "item": {"name": "policies", "ou": "Policies"}, "msg": "Entry action failed."}
        to retry, use: --limit @/root/IdP3-ansible/playbook.retry

**Comment by malavolti** [comment]
Quello che hai incontrato è un BUG dell'ultima versione di Ansible la cui soluzione te la riporto qui:
https://github.com/ansible/ansible/pull/47026/files

Applicando la modifica sopracitata l'esecuzione della ricetta torna ad eseguirsi correttamente.

**Comment by UniBean** [comment]
Grazie Marco,
ho effettuato la modifica che mi hai indicato e tutto ha funzionato alla perfezione.
